<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $vendors = User::where('role', 'vendor')->get();
        $categories = Category::whereNull('parent_id')->get();

        if ($vendors->isEmpty() || $categories->isEmpty()) {
            $this->command->error('No vendors or categories found. Run UserSeeder and CategorySeeder first.');

            return;
        }

        $products = $this->getProducts();

        foreach ($products as $productData) {
            $category = $this->getCategoryForProduct($productData['name'], $categories);
            $vendor = $vendors->random();
            $slug = Str::slug($productData['name']);

            Product::firstOrCreate(
                ['slug' => $slug],
                array_merge($productData, [
                    'category_id' => $category->id,
                    'vendor_id' => $vendor->id,
                ])
            );
        }

        $this->command->info('Successfully seeded ' . count($products) . ' products.');
    }

    private function getCategoryForProduct(string $productName, $categories): Category
    {
        $lower = strtolower($productName);

        $categoryKeywords = [
            'dairy-eggs' => ['milk', 'yogurt', 'cheese', 'cream', 'butter', 'egg', 'whey', 'cottage', 'feta', 'mozzarella', 'parmesan', 'ricotta', 'whipped cream'],
            'fresh-produce' => ['banana', 'apple', 'orange', 'strawberry', 'blueberry', 'mango', 'pineapple', 'watermelon', 'avocado', 'spinach', 'kale', 'broccoli', 'carrot', 'cucumber', 'tomato', 'lemon', 'bell pepper', 'sweet potato'],
            'meat-seafood' => ['salmon', 'chicken', 'beef', 'pork', 'shrimp', 'tuna', 'cod'],
            'bakery' => ['bread', 'oat bread', 'sourdough'],
            'health-wellness' => ['protein', 'vitamin', 'collagen', 'probiotic', 'omega-3', 'magnesium', 'turmeric', 'curcumin', 'elderberry', 'spirulina', 'chlorella', 'ashwagandha', 'maca', 'vitamin d'],
            'pantry-staples' => ['rice', 'pasta', 'quinoa', 'lentil', 'bean', 'chickpea', 'flour', 'oats', 'barley', 'millet', 'buckwheat', 'amaranth', 'wild rice'],
            'snacks' => ['almond', 'cashew', 'walnut', 'pecan', 'pistachio', 'granola', 'muesli', 'cornflakes', 'trail mix'],
            'beverages' => ['tea', 'coffee', 'juice', 'kombucha', 'sparkling', 'smoothie'],
            'frozen-foods' => ['frozen', 'edamame'],
            'specialty-diet' => ['gluten-free', 'vegan', 'keto', 'paleo', 'plant-based', 'hemp'],
        ];

        foreach ($categoryKeywords as $slug => $keywords) {
            foreach ($keywords as $keyword) {
                if (str_contains($lower, $keyword)) {
                    $match = $categories->firstWhere('slug', $slug);
                    if ($match) {
                        return $match;
                    }
                }
            }
        }

        return $categories->random();
    }

    private function getProducts(): array
    {
        return [
            [
                'name' => 'Organic Almond Milk Unsweetened',
                'description' => 'Fresh organic almond milk with no added sugar. Perfect for smoothies, coffee, and cereals. Dairy-free and low calorie.',
                'price' => 4.99,
                'compare_at_price' => 6.49,
                'image_url' => 'images/products/organic-almond-milk-unsweetened.jpg',
                'stock_quantity' => 150,
                'is_active' => true,
                'is_featured' => true,
                'nutrition_data' => $this->nutrition(30, 1, 1, 2.5, 0, 0, ['tree nuts']),
                'sku' => 'BEV-ALM-001',
                'weight_kg' => 1.0,
            ],
            [
                'name' => 'Organic Greek Yogurt Plain',
                'description' => 'Creamy organic Greek-style yogurt with no added sugar. High in protein and probiotics for gut health.',
                'price' => 5.49,
                'compare_at_price' => 6.99,
                'image_url' => 'images/products/organic-greek-yogurt-plain.jpg',
                'stock_quantity' => 200,
                'is_active' => true,
                'is_featured' => true,
                'nutrition_data' => $this->nutrition(100, 17, 6, 0.5, 4, 0, ['dairy']),
                'sku' => 'DAI-YOG-001',
                'weight_kg' => 0.5,
            ],
            [
                'name' => 'Grass-Fed Whey Protein Isolate',
                'description' => 'Premium grass-fed whey protein isolate for muscle building and recovery. 25g protein per serving with minimal fats.',
                'price' => 39.99,
                'compare_at_price' => 49.99,
                'image_url' => 'images/products/grass-fed-whey-protein-isolate.jpg',
                'stock_quantity' => 75,
                'is_active' => true,
                'is_featured' => true,
                'nutrition_data' => $this->nutrition(120, 25, 2, 1, 1, 0, ['dairy']),
                'sku' => 'HLT-PRO-001',
                'weight_kg' => 0.5,
            ],
            [
                'name' => 'Organic Quinoa Grain',
                'description' => 'Premium organic quinoa grain. High in protein, fiber, and essential amino acids. Naturally gluten-free superfood.',
                'price' => 8.99,
                'compare_at_price' => 11.49,
                'image_url' => 'images/products/organic-quinoa-grain.jpg',
                'stock_quantity' => 200,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(222, 8, 39, 3.5, 0, 5, []),
                'sku' => 'PAN-QUI-001',
                'weight_kg' => 0.5,
            ],
            [
                'name' => 'Organic Chia Seeds Premium',
                'description' => 'Premium organic chia seeds packed with omega-3 fatty acids, fiber, and plant-based protein.',
                'price' => 9.99,
                'compare_at_price' => 12.99,
                'image_url' => 'images/products/organic-chia-seeds-premium.jpg',
                'stock_quantity' => 180,
                'is_active' => true,
                'is_featured' => true,
                'nutrition_data' => $this->nutrition(138, 5, 12, 9, 0, 10, []),
                'sku' => 'SNK-CHI-001',
                'weight_kg' => 0.4,
            ],
            [
                'name' => 'Organic Avocado Oil',
                'description' => 'Cold-pressed organic avocado oil. Perfect for cooking, salad dressings, and skincare. High smoke point.',
                'price' => 12.99,
                'image_url' => 'images/products/organic-avocado-oil-spray.jpg',
                'stock_quantity' => 100,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(120, 0, 0, 14, 0, 0, []),
                'sku' => 'PAN-AVO-001',
                'weight_kg' => 0.5,
            ],
            [
                'name' => 'Organic Rolled Oats',
                'description' => 'Whole grain organic rolled oats. Perfect for overnight oats, granola, and hearty breakfast bowls.',
                'price' => 6.49,
                'compare_at_price' => 7.99,
                'image_url' => 'images/products/organic-rolled-oats.jpg',
                'stock_quantity' => 250,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(150, 5, 27, 3, 1, 4, []),
                'sku' => 'PAN-OAT-001',
                'weight_kg' => 0.5,
            ],
            [
                'name' => 'Organic Bananas',
                'description' => 'Fresh organic bananas. Naturally sweet, rich in potassium, and perfect for smoothies or snacking.',
                'price' => 1.99,
                'image_url' => 'images/products/organic-bananas.jpg',
                'stock_quantity' => 500,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(105, 1.3, 27, 0.4, 14, 3.1, []),
                'sku' => 'PRD-BAN-001',
                'weight_kg' => 1.0,
            ],
            [
                'name' => 'Organic Baby Spinach',
                'description' => 'Tender organic baby spinach leaves. Perfect for salads, smoothies, and sauteed side dishes.',
                'price' => 3.99,
                'image_url' => 'images/products/organic-baby-spinach.jpg',
                'stock_quantity' => 150,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(23, 2.9, 3.6, 0.4, 0.4, 2.2, []),
                'sku' => 'PRD-SPN-001',
                'weight_kg' => 0.25,
            ],
            [
                'name' => 'Organic Blueberries Fresh',
                'description' => 'Plump fresh organic blueberries. Packed with antioxidants, vitamins, and natural sweetness.',
                'price' => 4.99,
                'compare_at_price' => 5.99,
                'image_url' => 'images/products/organic-blueberries-fresh.jpg',
                'stock_quantity' => 120,
                'is_active' => true,
                'is_featured' => true,
                'nutrition_data' => $this->nutrition(84, 1.1, 21, 0.5, 15, 3.6, []),
                'sku' => 'PRD-BLU-001',
                'weight_kg' => 0.2,
            ],
            [
                'name' => 'Organic Strawberries',
                'description' => 'Sweet and juicy organic strawberries. Perfect for desserts, smoothies, and fresh snacking.',
                'price' => 5.49,
                'image_url' => 'images/products/organic-strawberries.jpg',
                'stock_quantity' => 130,
                'is_active' => true,
                'is_featured' => true,
                'nutrition_data' => $this->nutrition(49, 1, 12, 0.5, 7, 3, []),
                'sku' => 'PRD-STR-001',
                'weight_kg' => 0.25,
            ],
            [
                'name' => 'Organic Avocados Hass',
                'description' => 'Premium organic Hass avocados. Creamy, buttery texture perfect for guacamole, toast, and salads.',
                'price' => 2.49,
                'image_url' => 'images/products/organic-avocados-hass.jpg',
                'stock_quantity' => 300,
                'is_active' => true,
                'is_featured' => true,
                'nutrition_data' => $this->nutrition(160, 2, 9, 15, 0.7, 7, []),
                'sku' => 'PRD-AVO-001',
                'weight_kg' => 0.2,
            ],
            [
                'name' => 'Organic Lemons',
                'description' => 'Fresh organic lemons. Perfect for cooking, baking, beverages, and natural cleaning.',
                'price' => 1.49,
                'image_url' => 'images/products/organic-lemons.jpg',
                'stock_quantity' => 400,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(17, 0.6, 5, 0.2, 1.5, 1.6, []),
                'sku' => 'PRD-LEM-001',
                'weight_kg' => 0.5,
            ],
            [
                'name' => 'Organic Oranges Navel',
                'description' => 'Sweet and juicy organic navel oranges. Seedless, easy to peel, and rich in Vitamin C.',
                'price' => 2.99,
                'image_url' => 'images/products/organic-oranges-navel.jpg',
                'stock_quantity' => 350,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(62, 1.2, 15, 0.2, 12, 3, []),
                'sku' => 'PRD-ORA-001',
                'weight_kg' => 1.0,
            ],
            [
                'name' => 'Organic Mango Fresh',
                'description' => 'Ripe organic mangoes. Tropical sweetness packed with vitamins A and C for immune support.',
                'price' => 3.49,
                'image_url' => 'images/products/organic-mango-fresh.jpg',
                'stock_quantity' => 200,
                'is_active' => true,
                'is_featured' => true,
                'nutrition_data' => $this->nutrition(99, 1.4, 25, 0.6, 23, 1.6, []),
                'sku' => 'PRD-MAN-001',
                'weight_kg' => 0.4,
            ],
            [
                'name' => 'Organic Pineapple Whole',
                'description' => 'Sweet organic whole pineapple. Rich in bromelain enzyme for digestion and vitamin C.',
                'price' => 4.49,
                'image_url' => 'images/products/organic-pineapple-whole.jpg',
                'stock_quantity' => 100,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(82, 0.9, 22, 0.2, 16, 2.3, []),
                'sku' => 'PRD-PIN-001',
                'weight_kg' => 1.5,
            ],
            [
                'name' => 'Organic Watermelon Slice',
                'description' => 'Refreshing organic watermelon slice. Hydrating, low calorie, and naturally sweet summer fruit.',
                'price' => 2.99,
                'image_url' => 'images/products/organic-watermelon-slice.jpg',
                'stock_quantity' => 150,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(30, 0.6, 8, 0.2, 6, 0.4, []),
                'sku' => 'PRD-WAT-001',
                'weight_kg' => 1.0,
            ],
            [
                'name' => 'Organic Broccoli Crowns',
                'description' => 'Fresh organic broccoli crowns. Rich in vitamins K and C, fiber, and powerful antioxidants.',
                'price' => 2.99,
                'image_url' => 'images/products/organic-broccoli-crowns.jpg',
                'stock_quantity' => 180,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(55, 3.7, 11, 0.6, 3, 5.1, []),
                'sku' => 'PRD-BRO-001',
                'weight_kg' => 0.5,
            ],
            [
                'name' => 'Organic Carrots Baby',
                'description' => 'Sweet and crunchy organic baby carrots. Perfect for snacking, salads, and cooking.',
                'price' => 2.49,
                'image_url' => 'images/products/organic-carrots-baby.jpg',
                'stock_quantity' => 300,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(41, 0.9, 10, 0.2, 4.7, 2.8, []),
                'sku' => 'PRD-CAR-001',
                'weight_kg' => 0.3,
            ],
            [
                'name' => 'Organic Cucumbers English',
                'description' => 'Crisp organic English cucumbers. Seedless, thin-skinned, and perfect for salads and sandwiches.',
                'price' => 1.99,
                'image_url' => 'images/products/organic-cucumbers-english.jpg',
                'stock_quantity' => 250,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(16, 0.7, 3.6, 0.1, 1.7, 0.5, []),
                'sku' => 'PRD-CUC-001',
                'weight_kg' => 0.4,
            ],
            [
                'name' => 'Organic Cherry Tomatoes',
                'description' => 'Sweet organic cherry tomatoes. Bursting with flavor, perfect for salads, pasta, and snacking.',
                'price' => 3.49,
                'image_url' => 'images/products/organic-cherry-tomatoes.jpg',
                'stock_quantity' => 200,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(18, 0.9, 3.9, 0.2, 2.6, 1.2, []),
                'sku' => 'PRD-CHR-001',
                'weight_kg' => 0.25,
            ],
            [
                'name' => 'Organic Red Bell Peppers',
                'description' => 'Vibrant organic red bell peppers. Sweet, crunchy, and loaded with vitamin C and antioxidants.',
                'price' => 2.49,
                'image_url' => 'images/products/organic-red-bell-peppers.jpg',
                'stock_quantity' => 180,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(31, 1, 6, 0.3, 4.2, 2.1, []),
                'sku' => 'PRD-BEL-001',
                'weight_kg' => 0.3,
            ],
            [
                'name' => 'Organic Kale Bunch',
                'description' => 'Fresh organic kale bunch. Nutrient-dense superfood rich in vitamins A, K, and calcium.',
                'price' => 2.99,
                'image_url' => 'images/products/organic-kale-bunch.jpg',
                'stock_quantity' => 150,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(33, 2.9, 6, 0.6, 1, 2.6, []),
                'sku' => 'PRD-KAL-001',
                'weight_kg' => 0.3,
            ],
            [
                'name' => 'Organic Sweet Potatoes',
                'description' => 'Organic sweet potatoes. Rich in beta-carotene, fiber, and complex carbohydrates. Naturally sweet.',
                'price' => 2.49,
                'image_url' => 'images/products/organic-sweet-potatoes.jpg',
                'stock_quantity' => 250,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(86, 1.6, 20, 0.1, 4.2, 3, []),
                'sku' => 'PRD-SWT-001',
                'weight_kg' => 1.0,
            ],
            [
                'name' => 'Organic Almonds Raw',
                'description' => 'Premium organic raw almonds. Rich in healthy fats, protein, vitamin E, and magnesium.',
                'price' => 12.99,
                'compare_at_price' => 15.99,
                'image_url' => 'images/products/organic-almonds-raw.jpg',
                'stock_quantity' => 200,
                'is_active' => true,
                'is_featured' => true,
                'nutrition_data' => $this->nutrition(164, 6, 6, 14, 1.2, 3.5, ['tree nuts']),
                'sku' => 'SNK-ALM-001',
                'weight_kg' => 0.3,
            ],
            [
                'name' => 'Organic Cashews Raw',
                'description' => 'Organic raw cashews. Creamy texture, rich in copper, magnesium, and healthy monounsaturated fats.',
                'price' => 13.99,
                'image_url' => 'images/products/organic-cashews-raw.jpg',
                'stock_quantity' => 175,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(157, 5, 9, 12, 1.7, 0.9, ['tree nuts']),
                'sku' => 'SNK-CSH-001',
                'weight_kg' => 0.3,
            ],
            [
                'name' => 'Organic Walnuts Halves',
                'description' => 'Premium organic walnut halves. Excellent source of omega-3 ALA, antioxidants, and brain-healthy nutrients.',
                'price' => 11.99,
                'image_url' => 'images/products/organic-walnuts-halves.jpg',
                'stock_quantity' => 160,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(185, 4.3, 3.9, 18.5, 0.7, 1.9, ['tree nuts']),
                'sku' => 'SNK-WAL-001',
                'weight_kg' => 0.3,
            ],
            [
                'name' => 'Organic Pecans Halves',
                'description' => 'Organic pecan halves. Buttery, sweet flavor with high antioxidant content and heart-healthy fats.',
                'price' => 14.99,
                'image_url' => 'images/products/organic-pecans-halves.jpg',
                'stock_quantity' => 140,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(196, 2.6, 3.9, 20.4, 1.1, 2.7, ['tree nuts']),
                'sku' => 'SNK-PEC-001',
                'weight_kg' => 0.3,
            ],
            [
                'name' => 'Organic Pistachios Roasted',
                'description' => 'Dry roasted organic pistachios. Naturally sweet, rich in protein, fiber, and potassium.',
                'price' => 13.49,
                'image_url' => 'images/products/organic-pistachios-roasted.jpg',
                'stock_quantity' => 150,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(161, 6, 8, 13, 2.2, 3, ['tree nuts']),
                'sku' => 'SNK-PIS-001',
                'weight_kg' => 0.3,
            ],
            [
                'name' => 'Organic Peanut Butter Creamy',
                'description' => 'Smooth organic peanut butter. Made from 100% organic peanuts with no added sugar or oils.',
                'price' => 7.99,
                'compare_at_price' => 9.99,
                'image_url' => 'images/products/organic-peanut-butter-creamy.jpg',
                'stock_quantity' => 220,
                'is_active' => true,
                'is_featured' => true,
                'nutrition_data' => $this->nutrition(188, 8, 6, 16, 3, 2, ['peanuts']),
                'sku' => 'SNK-PNB-001',
                'weight_kg' => 0.5,
            ],
            [
                'name' => 'Organic Almond Butter',
                'description' => 'Creamy organic almond butter. Rich, nutty flavor with more vitamins and minerals than peanut butter.',
                'price' => 11.99,
                'image_url' => 'images/products/organic-almond-butter.jpg',
                'stock_quantity' => 150,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(196, 7, 7, 18, 1.8, 3.4, ['tree nuts']),
                'sku' => 'SNK-ALB-001',
                'weight_kg' => 0.4,
            ],
            [
                'name' => 'Organic Cashew Butter',
                'description' => 'Smooth organic cashew butter. Creamy texture with a mild, sweet flavor. Great on toast and in smoothies.',
                'price' => 12.49,
                'image_url' => 'images/products/organic-cashew-butter.jpg',
                'stock_quantity' => 130,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(190, 5, 9, 16, 2, 1, ['tree nuts']),
                'sku' => 'SNK-CAB-001',
                'weight_kg' => 0.4,
            ],
            [
                'name' => 'Organic Pumpkin Seeds',
                'description' => 'Raw organic pumpkin seeds. Excellent source of zinc, magnesium, and plant-based iron.',
                'price' => 8.99,
                'image_url' => 'images/products/organic-pumpkin-seeds.jpg',
                'stock_quantity' => 190,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(151, 7, 5, 13, 0.4, 1.7, []),
                'sku' => 'SNK-PUM-001',
                'weight_kg' => 0.3,
            ],
            [
                'name' => 'Organic Sunflower Seeds',
                'description' => 'Organic raw sunflower seeds. Rich in vitamin E, selenium, and healthy fats.',
                'price' => 6.99,
                'image_url' => 'images/products/organic-sunflower-seeds.jpg',
                'stock_quantity' => 200,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(164, 5.8, 7, 14, 0.8, 3.7, []),
                'sku' => 'SNK-SUN-001',
                'weight_kg' => 0.3,
            ],
            [
                'name' => 'Organic Hemp Seeds',
                'description' => 'Organic hulled hemp seeds (hemp hearts). Complete protein with all 9 essential amino acids and omega fatty acids.',
                'price' => 12.99,
                'image_url' => 'images/products/organic-hemp-seeds.jpg',
                'stock_quantity' => 140,
                'is_active' => true,
                'is_featured' => true,
                'nutrition_data' => $this->nutrition(170, 10, 3, 14, 0.5, 1, []),
                'sku' => 'SNK-HEM-001',
                'weight_kg' => 0.3,
            ],
            [
                'name' => 'Organic Flaxseeds Ground',
                'description' => 'Organic ground flaxseeds. Rich in omega-3 ALA, lignans, and soluble fiber for heart health.',
                'price' => 7.49,
                'image_url' => 'images/products/organic-flaxseeds-ground.jpg',
                'stock_quantity' => 180,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(150, 5, 8, 12, 0.4, 8, []),
                'sku' => 'SNK-FLX-001',
                'weight_kg' => 0.4,
            ],
            [
                'name' => 'Organic Granola Mixed Berry',
                'description' => 'Crunchy organic granola with mixed berries. Made with rolled oats, nuts, seeds, and freeze-dried berries.',
                'price' => 8.99,
                'compare_at_price' => 10.99,
                'image_url' => 'images/products/organic-granola-mixed-berry.jpg',
                'stock_quantity' => 160,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(210, 5, 32, 7, 8, 3, ['tree nuts']),
                'sku' => 'SNK-GRN-001',
                'weight_kg' => 0.4,
            ],
            [
                'name' => 'Organic Muesli Original',
                'description' => 'Traditional organic muesli blend. Raw rolled oats, nuts, seeds, and dried fruits for a wholesome breakfast.',
                'price' => 7.99,
                'image_url' => 'images/products/organic-muesli-original.jpg',
                'stock_quantity' => 170,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(180, 6, 30, 4, 7, 4, ['tree nuts']),
                'sku' => 'SNK-MUE-001',
                'weight_kg' => 0.5,
            ],
            [
                'name' => 'Organic Cornflakes',
                'description' => 'Classic organic cornflakes cereal. Light, crispy, and made from organic corn. Perfect with milk or yogurt.',
                'price' => 4.99,
                'image_url' => 'images/products/organic-cornflakes.jpg',
                'stock_quantity' => 200,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(101, 2, 24, 0.2, 2.3, 0.7, []),
                'sku' => 'SNK-COR-001',
                'weight_kg' => 0.4,
            ],
            [
                'name' => 'Organic Brown Rice',
                'description' => 'Premium organic brown rice. Whole grain with bran and germ intact. Rich in fiber, manganese, and selenium.',
                'price' => 5.99,
                'image_url' => 'images/products/organic-brown-rice.jpg',
                'stock_quantity' => 250,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(216, 5, 45, 1.8, 0.7, 3.5, []),
                'sku' => 'PAN-BRN-001',
                'weight_kg' => 1.0,
            ],
            [
                'name' => 'Organic Whole Wheat Pasta',
                'description' => 'Organic whole wheat pasta. Made from durum wheat semolina with all the fiber and nutrients intact.',
                'price' => 3.99,
                'image_url' => 'images/products/organic-whole-wheat-pasta.jpg',
                'stock_quantity' => 220,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(174, 7.5, 37, 0.8, 0.8, 6.3, ['gluten']),
                'sku' => 'PAN-PST-001',
                'weight_kg' => 0.5,
            ],
            [
                'name' => 'Organic Quinoa Pasta',
                'description' => 'Gluten-free organic quinoa pasta. Made from 100% quinoa flour with a nutty flavor and firm texture.',
                'price' => 5.49,
                'image_url' => 'images/products/organic-quinoa-pasta.jpg',
                'stock_quantity' => 180,
                'is_active' => true,
                'is_featured' => true,
                'nutrition_data' => $this->nutrition(180, 4, 39, 1.5, 1, 3, []),
                'sku' => 'PAN-QPA-001',
                'weight_kg' => 0.4,
            ],
            [
                'name' => 'Organic Rice Noodles',
                'description' => 'Organic rice noodles. Gluten-free, light and silky. Perfect for stir-fries, pho, and pad thai.',
                'price' => 4.49,
                'image_url' => 'images/products/organic-rice-noodles.jpg',
                'stock_quantity' => 200,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(192, 3.6, 44, 0.2, 0, 1.8, []),
                'sku' => 'PAN-RNO-001',
                'weight_kg' => 0.4,
            ],
            [
                'name' => 'Organic Lentils Red',
                'description' => 'Organic red lentils. Quick-cooking, high in protein and folate. Perfect for soups, curries, and dals.',
                'price' => 4.99,
                'image_url' => 'images/products/organic-lentils-red.jpg',
                'stock_quantity' => 250,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(230, 18, 40, 0.8, 3.3, 15.6, []),
                'sku' => 'PAN-LEN-001',
                'weight_kg' => 0.5,
            ],
            [
                'name' => 'Organic Black Beans Canned',
                'description' => 'Organic black beans, ready to eat. Rich in protein, fiber, and antioxidants. Great for burritos and salads.',
                'price' => 2.49,
                'image_url' => 'images/products/organic-black-beans-canned.jpg',
                'stock_quantity' => 300,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(114, 7.6, 20, 0.5, 0.3, 7.5, []),
                'sku' => 'PAN-BLB-001',
                'weight_kg' => 0.4,
            ],
            [
                'name' => 'Organic Chickpeas Canned',
                'description' => 'Organic chickpeas (garbanzo beans). Versatile, protein-rich legume for hummus, salads, and curries.',
                'price' => 2.49,
                'image_url' => 'images/products/organic-chickpeas-canned.jpg',
                'stock_quantity' => 300,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(139, 7.5, 23, 2.3, 4, 5.8, []),
                'sku' => 'PAN-CHK-001',
                'weight_kg' => 0.4,
            ],
            [
                'name' => 'Organic Whole Wheat Flour',
                'description' => 'Stone-ground organic whole wheat flour. Perfect for bread, muffins, and all baking needs.',
                'price' => 4.99,
                'image_url' => 'images/products/organic-whole-wheat-flour.jpg',
                'stock_quantity' => 200,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(407, 13.2, 72, 2.2, 0.4, 12.2, ['gluten']),
                'sku' => 'PAN-WHF-001',
                'weight_kg' => 1.0,
            ],
            [
                'name' => 'Organic Coconut Flour',
                'description' => 'Organic coconut flour. Gluten-free, high in fiber and protein. Perfect for paleo and keto baking.',
                'price' => 8.49,
                'image_url' => 'images/products/organic-coconut-flour.jpg',
                'stock_quantity' => 150,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(400, 19, 57, 14, 10, 38, []),
                'sku' => 'PAN-COF-001',
                'weight_kg' => 0.5,
            ],
            [
                'name' => 'Organic Almond Flour',
                'description' => 'Finely ground organic almond flour. Gluten-free, low-carb alternative for baking. Rich and nutty.',
                'price' => 12.99,
                'compare_at_price' => 15.49,
                'image_url' => 'images/products/organic-almond-flour.jpg',
                'stock_quantity' => 130,
                'is_active' => true,
                'is_featured' => true,
                'nutrition_data' => $this->nutrition(163, 6, 6, 14, 1.2, 3, ['tree nuts']),
                'sku' => 'PAN-ALF-001',
                'weight_kg' => 0.4,
            ],
            [
                'name' => 'Organic Coconut Oil Virgin',
                'description' => 'Unrefined organic virgin coconut oil. Cold-pressed, perfect for cooking, baking, and skincare.',
                'price' => 9.99,
                'image_url' => 'images/products/organic-coconut-oil-virgin.jpg',
                'stock_quantity' => 180,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(121, 0, 0, 14, 0, 0, []),
                'sku' => 'PAN-COO-001',
                'weight_kg' => 0.5,
            ],
            [
                'name' => 'Organic Olive Oil Extra Virgin',
                'description' => 'Premium cold-pressed organic extra virgin olive oil. Rich in monounsaturated fats and antioxidants.',
                'price' => 14.99,
                'compare_at_price' => 18.99,
                'image_url' => 'images/products/cold-pressed-olive-oil-extra-virgin.jpg',
                'stock_quantity' => 120,
                'is_active' => true,
                'is_featured' => true,
                'nutrition_data' => $this->nutrition(119, 0, 0, 14, 0, 0, []),
                'sku' => 'PAN-OLI-001',
                'weight_kg' => 0.5,
            ],
            [
                'name' => 'Organic Sesame Oil Toasted',
                'description' => 'Organic toasted sesame oil. Rich, nutty flavor perfect for Asian cuisine, stir-fries, and dressings.',
                'price' => 7.99,
                'image_url' => 'images/products/organic-sesame-oil-toasted.jpg',
                'stock_quantity' => 150,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(120, 0, 0, 14, 0, 0, []),
                'sku' => 'PAN-SES-001',
                'weight_kg' => 0.3,
            ],
            [
                'name' => 'Organic Maple Syrup Pure',
                'description' => '100% pure organic maple syrup. Grade A dark color with robust flavor. Natural sweetener for pancakes and baking.',
                'price' => 11.99,
                'image_url' => 'images/products/organic-maple-syrup-pure.jpg',
                'stock_quantity' => 100,
                'is_active' => true,
                'is_featured' => true,
                'nutrition_data' => $this->nutrition(52, 0, 13, 0.1, 12, 0, []),
                'sku' => 'PAN-MAP-001',
                'weight_kg' => 0.4,
            ],
            [
                'name' => 'Organic Agave Nectar',
                'description' => 'Organic agave nectar. Low glycemic natural sweetener. Vegan honey alternative for beverages and baking.',
                'price' => 8.99,
                'image_url' => 'images/products/organic-agave-nectar.jpg',
                'stock_quantity' => 130,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(60, 0, 16, 0, 15, 0, []),
                'sku' => 'PAN-AGV-001',
                'weight_kg' => 0.4,
            ],
            [
                'name' => 'Organic Apple Cider Vinegar',
                'description' => 'Raw, unfiltered organic apple cider vinegar with the mother. Perfect for dressings, marinades, and wellness shots.',
                'price' => 6.99,
                'image_url' => 'images/products/organic-apple-cider-vinegar.jpg',
                'stock_quantity' => 200,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(3, 0, 0.1, 0, 0, 0, []),
                'sku' => 'PAN-ACV-001',
                'weight_kg' => 0.5,
            ],
            [
                'name' => 'Organic Balsamic Vinegar',
                'description' => 'Aged organic balsamic vinegar. Sweet and tangy, perfect for salads, glazes, and Italian dishes.',
                'price' => 9.99,
                'image_url' => 'images/products/organic-balsamic-vinegar.jpg',
                'stock_quantity' => 150,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(14, 0.1, 3, 0, 2.4, 0, []),
                'sku' => 'PAN-BAL-001',
                'weight_kg' => 0.3,
            ],
            [
                'name' => 'Organic Coconut Aminos',
                'description' => 'Organic coconut aminos. Soy-free, gluten-free alternative to soy sauce. Naturally sweet and savory.',
                'price' => 7.49,
                'image_url' => 'images/products/organic-coconut-aminos.jpg',
                'stock_quantity' => 160,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(15, 1, 3, 0, 2, 0, []),
                'sku' => 'PAN-COA-001',
                'weight_kg' => 0.3,
            ],
            [
                'name' => 'Organic Tahini Sesame Paste',
                'description' => 'Smooth organic tahini paste made from roasted sesame seeds. Essential for hummus, dressings, and Middle Eastern cooking.',
                'price' => 9.49,
                'image_url' => 'images/products/organic-tahini-sesame-paste.jpg',
                'stock_quantity' => 140,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(178, 5, 6, 16, 0.1, 2.7, []),
                'sku' => 'PAN-THN-001',
                'weight_kg' => 0.4,
            ],
            [
                'name' => 'Organic Coconut Milk Canned',
                'description' => 'Full-fat organic coconut milk. Creamy and rich, perfect for curries, soups, smoothies, and desserts.',
                'price' => 3.49,
                'image_url' => 'images/products/organic-coconut-milk-canned.jpg',
                'stock_quantity' => 250,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(230, 2.3, 6, 24, 3.3, 2.2, []),
                'sku' => 'BEV-COC-001',
                'weight_kg' => 0.4,
            ],
            [
                'name' => 'Organic Cashew Milk',
                'description' => 'Creamy organic cashew milk. Dairy-free, low calorie, and perfect for coffee, cereal, and smoothies.',
                'price' => 5.49,
                'image_url' => 'images/products/organic-cashew-milk.jpg',
                'stock_quantity' => 180,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(25, 0.5, 2, 2, 0, 0, ['tree nuts']),
                'sku' => 'BEV-CSM-001',
                'weight_kg' => 1.0,
            ],
            [
                'name' => 'Organic Soy Milk Unsweetened',
                'description' => 'Organic unsweetened soy milk. High in protein, dairy-free alternative for drinking and cooking.',
                'price' => 4.49,
                'image_url' => 'images/products/organic-soy-milk-unsweetened.jpg',
                'stock_quantity' => 200,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(80, 7, 4, 4, 0.5, 1, ['soy']),
                'sku' => 'BEV-SOY-001',
                'weight_kg' => 1.0,
            ],
            [
                'name' => 'Organic Hemp Milk',
                'description' => 'Organic hemp milk with omega fatty acids. Creamy, nutty, and naturally dairy-free plant milk.',
                'price' => 5.99,
                'image_url' => 'images/products/organic-hemp-milk.jpg',
                'stock_quantity' => 160,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(60, 2, 7, 3, 0, 0, []),
                'sku' => 'BEV-HMP-001',
                'weight_kg' => 1.0,
            ],
            [
                'name' => 'Organic Rice Milk Original',
                'description' => 'Organic rice milk. Naturally sweet, hypoallergenic dairy-free milk alternative. Great for allergies.',
                'price' => 4.49,
                'image_url' => 'images/products/organic-rice-milk-original.jpg',
                'stock_quantity' => 180,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(120, 1, 23, 2.5, 10, 0.5, []),
                'sku' => 'BEV-RIC-001',
                'weight_kg' => 1.0,
            ],
            [
                'name' => 'Organic Green Tea Matcha',
                'description' => 'Ceremonial grade organic matcha green tea powder. Rich in L-theanine, antioxidants, and sustained energy.',
                'price' => 19.99,
                'compare_at_price' => 24.99,
                'image_url' => 'images/products/organic-green-tea-matcha.jpg',
                'stock_quantity' => 80,
                'is_active' => true,
                'is_featured' => true,
                'nutrition_data' => $this->nutrition(3, 0.2, 0.4, 0, 0, 0.3, []),
                'sku' => 'BEV-MTC-001',
                'weight_kg' => 0.1,
            ],
            [
                'name' => 'Organic Herbal Tea Chamomile',
                'description' => 'Soothing organic chamomile herbal tea. Caffeine-free, perfect for relaxation and bedtime.',
                'price' => 5.99,
                'image_url' => 'images/products/organic-herbal-tea-chamomile.jpg',
                'stock_quantity' => 200,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(0, 0, 0, 0, 0, 0, []),
                'sku' => 'BEV-CHM-001',
                'weight_kg' => 0.05,
            ],
            [
                'name' => 'Organic Kombucha Ginger',
                'description' => 'Organic ginger kombucha. Probiotic-rich fermented tea for gut health with a spicy ginger kick.',
                'price' => 4.49,
                'image_url' => 'images/products/organic-kombucha-ginger.jpg',
                'stock_quantity' => 120,
                'is_active' => true,
                'is_featured' => true,
                'nutrition_data' => $this->nutrition(30, 0, 7, 0, 6, 0, []),
                'sku' => 'BEV-KOM-001',
                'weight_kg' => 0.5,
            ],
            [
                'name' => 'Organic Sparkling Water Lemon',
                'description' => 'Refreshing organic sparkling water with natural lemon essence. Zero calories, zero sweeteners.',
                'price' => 1.49,
                'image_url' => 'images/products/organic-sparkling-water-lemon.jpg',
                'stock_quantity' => 500,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(0, 0, 0, 0, 0, 0, []),
                'sku' => 'BEV-SPR-001',
                'weight_kg' => 0.5,
            ],
            [
                'name' => 'Organic Butter Unsalted',
                'description' => 'Premium organic unsalted butter. Made from grass-fed cream. Perfect for baking and cooking.',
                'price' => 5.99,
                'image_url' => 'images/products/organic-butter-unsalted.jpg',
                'stock_quantity' => 200,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(102, 0.1, 0, 12, 0, 0, ['dairy']),
                'sku' => 'DAI-BUT-001',
                'weight_kg' => 0.25,
            ],
            [
                'name' => 'Organic Ghee Clarified',
                'description' => 'Organic grass-fed ghee (clarified butter). Lactose-free, high smoke point, rich in vitamins A, D, E, K.',
                'price' => 12.99,
                'image_url' => 'images/products/organic-ghee-clarified.jpg',
                'stock_quantity' => 100,
                'is_active' => true,
                'is_featured' => true,
                'nutrition_data' => $this->nutrition(120, 0, 0, 14, 0, 0, ['dairy']),
                'sku' => 'DAI-GHE-001',
                'weight_kg' => 0.3,
            ],
            [
                'name' => 'Organic Cottage Cheese',
                'description' => 'Creamy organic cottage cheese. High in protein and calcium, perfect for snacks and salads.',
                'price' => 4.99,
                'image_url' => 'images/products/organic-cottage-cheese.jpg',
                'stock_quantity' => 150,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(98, 11, 3.4, 4.3, 2.7, 0, ['dairy']),
                'sku' => 'DAI-COT-001',
                'weight_kg' => 0.3,
            ],
            [
                'name' => 'Organic Feta Cheese',
                'description' => 'Traditional organic feta cheese. Tangy, crumbly, perfect for salads, pastas, and Mediterranean dishes.',
                'price' => 6.49,
                'image_url' => 'images/products/organic-feta-cheese.jpg',
                'stock_quantity' => 130,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(75, 4, 1.2, 6, 0.4, 0, ['dairy']),
                'sku' => 'DAI-FET-001',
                'weight_kg' => 0.2,
            ],
            [
                'name' => 'Organic Mozzarella Fresh',
                'description' => 'Fresh organic mozzarella cheese. Soft, milky, and stretchy. Perfect for caprese, pizza, and pasta.',
                'price' => 6.99,
                'image_url' => 'images/products/organic-mozzarella-fresh.jpg',
                'stock_quantity' => 140,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(85, 6.3, 0.8, 6.3, 0.3, 0, ['dairy']),
                'sku' => 'DAI-MOZ-001',
                'weight_kg' => 0.2,
            ],
            [
                'name' => 'Organic Parmesan Cheese',
                'description' => 'Aged organic parmesan cheese. Rich, nutty, and umami-packed. Perfect for pasta, salads, and risotto.',
                'price' => 8.99,
                'image_url' => 'images/products/organic-parmesan-cheese.jpg',
                'stock_quantity' => 120,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(110, 10, 0.9, 7.3, 0, 0, ['dairy']),
                'sku' => 'DAI-PAR-001',
                'weight_kg' => 0.2,
            ],
            [
                'name' => 'Organic Ricotta Cheese',
                'description' => 'Creamy organic ricotta cheese. Light, mild, and versatile. Perfect for lasagna, stuffed shells, and desserts.',
                'price' => 5.99,
                'image_url' => 'images/products/organic-ricotta-cheese.jpg',
                'stock_quantity' => 130,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(86, 5.6, 3, 6, 1.5, 0, ['dairy']),
                'sku' => 'DAI-RIC-001',
                'weight_kg' => 0.3,
            ],
            [
                'name' => 'Organic Cream Cheese',
                'description' => 'Smooth organic cream cheese. Rich and spreadable. Perfect for bagels, cheesecakes, and dips.',
                'price' => 4.49,
                'image_url' => 'images/products/organic-cream-cheese.jpg',
                'stock_quantity' => 180,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(100, 2, 1, 10, 1, 0, ['dairy']),
                'sku' => 'DAI-CRM-001',
                'weight_kg' => 0.25,
            ],
            [
                'name' => 'Organic Whipped Cream',
                'description' => 'Premium organic whipped cream. Light and fluffy, perfect for desserts, hot cocoa, and fruit toppings.',
                'price' => 3.99,
                'image_url' => 'images/products/organic-whipped-cream.jpg',
                'stock_quantity' => 150,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(51, 0.3, 0.5, 5.5, 0.4, 0, ['dairy']),
                'sku' => 'DAI-WHC-001',
                'weight_kg' => 0.25,
            ],
            [
                'name' => 'Organic Gluten-Free Bread',
                'description' => 'Soft organic gluten-free bread. Made with rice flour, tapioca starch, and seeds. No artificial additives.',
                'price' => 6.99,
                'compare_at_price' => 8.49,
                'image_url' => 'images/products/organic-gluten-free-bread.jpg',
                'stock_quantity' => 80,
                'is_active' => true,
                'is_featured' => true,
                'nutrition_data' => $this->nutrition(110, 2, 20, 3, 3, 2, []),
                'sku' => 'BAK-GFB-001',
                'weight_kg' => 0.5,
            ],
            [
                'name' => 'Organic Sourdough Bread',
                'description' => 'Artisan organic sourdough bread. Naturally leavened with a tangy flavor and crispy crust.',
                'price' => 5.99,
                'image_url' => 'images/products/organic-sourdough-bread.jpg',
                'stock_quantity' => 60,
                'is_active' => true,
                'is_featured' => true,
                'nutrition_data' => $this->nutrition(120, 4, 24, 0.5, 1, 1, ['gluten']),
                'sku' => 'BAK-SDO-001',
                'weight_kg' => 0.6,
            ],
            [
                'name' => 'Organic Multigrain Bread',
                'description' => 'Hearty organic multigrain bread. Made with seven whole grains and seeds for maximum nutrition.',
                'price' => 5.49,
                'image_url' => 'images/products/organic-multigrain-bread.jpg',
                'stock_quantity' => 70,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(110, 5, 20, 2, 2, 3, ['gluten']),
                'sku' => 'BAK-MGR-001',
                'weight_kg' => 0.6,
            ],
            [
                'name' => 'Organic Tempeh Original',
                'description' => 'Traditional organic tempeh. Fermented soybean cake with a firm texture, nutty flavor, and complete protein.',
                'price' => 4.99,
                'image_url' => 'images/products/organic-tempeh-original.jpg',
                'stock_quantity' => 100,
                'is_active' => true,
                'is_featured' => true,
                'nutrition_data' => $this->nutrition(195, 20, 7.6, 11, 0, 0, ['soy']),
                'sku' => 'SPT-TMP-001',
                'weight_kg' => 0.2,
            ],
            [
                'name' => 'Organic Tofu Firm',
                'description' => 'Organic firm tofu. Versatile plant-based protein made from non-GMO soybeans. Great for stir-fries and grilling.',
                'price' => 3.49,
                'image_url' => 'images/products/organic-tofu-firm.jpg',
                'stock_quantity' => 180,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(144, 17, 2.8, 9, 0.6, 2.3, ['soy']),
                'sku' => 'SPT-TOF-001',
                'weight_kg' => 0.4,
            ],
            [
                'name' => 'Organic Edamame Frozen',
                'description' => 'Frozen organic edamame (young soybeans). Quick to prepare, high in protein, fiber, and vitamins.',
                'price' => 4.49,
                'image_url' => 'images/products/organic-edamame-frozen.jpg',
                'stock_quantity' => 150,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(121, 11.9, 8.9, 5.2, 2.2, 5.2, ['soy']),
                'sku' => 'FRZ-EDM-001',
                'weight_kg' => 0.3,
            ],
            [
                'name' => 'Organic Plant Protein Vanilla',
                'description' => 'Organic plant-based protein powder in vanilla flavor. Pea, brown rice, and chia protein blend.',
                'price' => 34.99,
                'compare_at_price' => 42.99,
                'image_url' => 'images/products/organic-plant-protein-vanilla.jpg',
                'stock_quantity' => 60,
                'is_active' => true,
                'is_featured' => true,
                'nutrition_data' => $this->nutrition(120, 22, 4, 2, 1, 3, []),
                'sku' => 'HLT-PLP-001',
                'weight_kg' => 0.5,
            ],
            [
                'name' => 'Organic Collagen Peptides',
                'description' => 'Grass-fed organic collagen peptides powder. Supports skin elasticity, joint health, and hair strength.',
                'price' => 29.99,
                'image_url' => 'images/products/organic-collagen-peptides.jpg',
                'stock_quantity' => 80,
                'is_active' => true,
                'is_featured' => true,
                'nutrition_data' => $this->nutrition(70, 18, 0, 0, 0, 0, []),
                'sku' => 'HLT-COL-001',
                'weight_kg' => 0.4,
            ],
            [
                'name' => 'Organic Probiotic Capsules',
                'description' => 'Organic probiotic supplement with 50 billion CFU. Supports gut health, immunity, and digestion.',
                'price' => 24.99,
                'image_url' => 'images/products/organic-probiotic-capsules.jpg',
                'stock_quantity' => 100,
                'is_active' => true,
                'is_featured' => true,
                'nutrition_data' => $this->nutrition(5, 0, 1, 0, 0, 0, []),
                'sku' => 'HLT-PRO-002',
                'weight_kg' => 0.05,
            ],
            [
                'name' => 'Organic Omega-3 Fish Oil',
                'description' => 'Wild-caught organic omega-3 fish oil. High EPA and DHA for heart, brain, and eye health.',
                'price' => 22.99,
                'image_url' => 'images/products/organic-omega-3-fish-oil.jpg',
                'stock_quantity' => 120,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(120, 0, 0, 14, 0, 0, ['fish']),
                'sku' => 'HLT-OMG-001',
                'weight_kg' => 0.2,
            ],
            [
                'name' => 'Organic Vitamin D3 Drops',
                'description' => 'Organic vitamin D3 liquid drops. 2000 IU per serving for bone health, immunity, and mood support.',
                'price' => 16.99,
                'image_url' => 'images/products/organic-vitamin-d3-drops.jpg',
                'stock_quantity' => 150,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(10, 0, 0, 1, 0, 0, []),
                'sku' => 'HLT-VD3-001',
                'weight_kg' => 0.03,
            ],
            [
                'name' => 'Organic Magnesium Glycinate',
                'description' => 'Highly bioavailable organic magnesium glycinate. Supports sleep, muscle relaxation, and nervous system.',
                'price' => 19.99,
                'image_url' => 'images/products/organic-magnesium-glycinate.jpg',
                'stock_quantity' => 130,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(0, 0, 0, 0, 0, 0, []),
                'sku' => 'HLT-MAG-001',
                'weight_kg' => 0.1,
            ],
            [
                'name' => 'Organic Turmeric Curcumin',
                'description' => 'Organic turmeric curcumin extract with black pepper. Anti-inflammatory and antioxidant support.',
                'price' => 18.99,
                'image_url' => 'images/products/organic-turmeric-curcumin.jpg',
                'stock_quantity' => 140,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(5, 0, 1, 0, 0, 0, []),
                'sku' => 'HLT-TUR-001',
                'weight_kg' => 0.08,
            ],
            [
                'name' => 'Organic Ashwagandha Root',
                'description' => 'Organic ashwagandha root extract. Adaptogenic herb for stress relief, energy, and cognitive support.',
                'price' => 17.99,
                'image_url' => 'images/products/organic-ashwagandha-root.jpg',
                'stock_quantity' => 110,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(5, 0, 1, 0, 0, 0, []),
                'sku' => 'HLT-ASH-001',
                'weight_kg' => 0.06,
            ],
            [
                'name' => 'Organic Maca Powder',
                'description' => 'Organic gelatinized maca root powder. Adaptogenic superfood for energy, stamina, and hormonal balance.',
                'price' => 15.99,
                'image_url' => 'images/products/organic-maca-powder.jpg',
                'stock_quantity' => 120,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(25, 1, 5, 0, 1, 1, []),
                'sku' => 'HLT-MAC-001',
                'weight_kg' => 0.2,
            ],
            [
                'name' => 'Organic Spirulina Powder',
                'description' => 'Organic spirulina blue-green algae powder. Nutrient-dense superfood rich in protein, iron, and B vitamins.',
                'price' => 19.99,
                'image_url' => 'images/products/organic-spirulina-powder.jpg',
                'stock_quantity' => 90,
                'is_active' => true,
                'is_featured' => true,
                'nutrition_data' => $this->nutrition(20, 4, 1.4, 0.6, 0.2, 0.3, []),
                'sku' => 'HLT-SPI-001',
                'weight_kg' => 0.15,
            ],
            [
                'name' => 'Organic Chlorella Tablets',
                'description' => 'Organic chlorella tablets. Detoxifying green superfood rich in chlorophyll, protein, and vitamins.',
                'price' => 21.99,
                'image_url' => 'images/products/organic-chlorella-tablets.jpg',
                'stock_quantity' => 100,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(15, 3, 1, 0.5, 0, 0.5, []),
                'sku' => 'HLT-CHL-001',
                'weight_kg' => 0.15,
            ],
            [
                'name' => 'Organic Elderberry Syrup',
                'description' => 'Organic elderberry syrup concentrate. Immune-boosting, rich in antioxidants and vitamin C.',
                'price' => 14.99,
                'image_url' => 'images/products/organic-elderberry-syrup.jpg',
                'stock_quantity' => 110,
                'is_active' => true,
                'is_featured' => true,
                'nutrition_data' => $this->nutrition(30, 0, 7, 0, 5, 0.5, []),
                'sku' => 'HLT-ELD-001',
                'weight_kg' => 0.3,
            ],
            [
                'name' => 'Organic Raw Wildflower Honey',
                'description' => 'Pure organic raw wildflower honey. Unprocessed, unpasteurized with natural enzymes and antioxidants.',
                'price' => 12.99,
                'compare_at_price' => 15.99,
                'image_url' => 'images/products/raw-wildflower-honey.jpg',
                'stock_quantity' => 150,
                'is_active' => true,
                'is_featured' => true,
                'nutrition_data' => $this->nutrition(64, 0.1, 17, 0, 17, 0, []),
                'sku' => 'PAN-HON-001',
                'weight_kg' => 0.4,
            ],
            [
                'name' => 'Organic Amaranth Grain',
                'description' => 'Organic amaranth ancient grain. Gluten-free, high in protein, lysine, calcium, and iron.',
                'price' => 7.49,
                'image_url' => 'images/products/organic-amaranth-grain.jpg',
                'stock_quantity' => 160,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(251, 9, 46, 7, 1.7, 6.7, []),
                'sku' => 'PAN-AMR-001',
                'weight_kg' => 0.5,
            ],
            [
                'name' => 'Organic Barley Pearled',
                'description' => 'Organic pearled barley. Hearty whole grain perfect for soups, stews, and pilafs. Rich in beta-glucan fiber.',
                'price' => 4.99,
                'image_url' => 'images/products/organic-barley-pearled.jpg',
                'stock_quantity' => 200,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(193, 4, 44, 0.7, 0.5, 6, ['gluten']),
                'sku' => 'PAN-BRL-001',
                'weight_kg' => 0.5,
            ],
            [
                'name' => 'Organic Buckwheat Groats',
                'description' => 'Organic buckwheat groats. Gluten-free pseudo-grain with a nutty flavor. High in rutin and complete protein.',
                'price' => 6.49,
                'image_url' => 'images/products/organic-buckwheat-groats.jpg',
                'stock_quantity' => 170,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(155, 6, 33, 1, 0, 5, []),
                'sku' => 'PAN-BKW-001',
                'weight_kg' => 0.5,
            ],
            [
                'name' => 'Organic Millet Hulled',
                'description' => 'Organic hulled millet. Ancient grain, gluten-free, alkalizing, and rich in magnesium and phosphorus.',
                'price' => 5.49,
                'image_url' => 'images/products/organic-millet-hulled.jpg',
                'stock_quantity' => 180,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(180, 6, 35, 1.5, 0, 3, []),
                'sku' => 'PAN-MIL-001',
                'weight_kg' => 0.5,
            ],
            [
                'name' => 'Organic Wild Rice',
                'description' => 'Premium organic wild rice. Nutty flavor, chewy texture, higher protein than regular rice. Lakeside harvested.',
                'price' => 9.99,
                'image_url' => 'images/products/organic-wild-rice.jpg',
                'stock_quantity' => 100,
                'is_active' => true,
                'is_featured' => false,
                'nutrition_data' => $this->nutrition(166, 6.5, 35, 0.6, 1, 3, []),
                'sku' => 'PAN-WLD-001',
                'weight_kg' => 0.4,
            ],
        ];
    }

    private function nutrition(float $cal, float $pro, float $carb, float $fat, float $sugar, float $fiber, array $allergens): array
    {
        return [
            'calories' => $cal,
            'protein' => $pro,
            'carbs' => $carb,
            'fats' => $fat,
            'sugar' => $sugar,
            'fiber' => $fiber,
            'allergens' => $allergens,
        ];
    }
}
